# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Publish to surge.sh
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to poor-brew.surge.sh
        uses: 
          - dswistowski/surge-sh-action@v1
          - actions/checkout@v2
        with:
          domain: 'poor-view.surge.sh'
          project: '$GITHUB_WORKSPACE'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
